// Runs against dedicated test data. See README.md before running.
const {chromium}=require(process.env.DIWAN_PLAYWRIGHT || 'playwright-core');
const assert=require('node:assert/strict');
const base = process.env.DIWAN_UI_URL;
const cdpUrl = process.env.DIWAN_UI_CDP;
if (!base || !cdpUrl) throw new Error('Set DIWAN_UI_URL and DIWAN_UI_CDP for an authenticated test browser.');
(async()=>{
 const browser=await chromium.connectOverCDP(cdpUrl);
 const context=browser.contexts()[0], page=await context.newPage();
 const cdp=await context.newCDPSession(page);
 await cdp.send('Network.clearBrowserCache');
 await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(base+'/diwan/submit?_lang=en',{waitUntil:'networkidle'});
 await page.locator('#submit-btn').click();
 assert.equal(await page.locator('#field-subject').getAttribute('aria-invalid'),'true');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'field-subject');
 await page.locator('#field-subject').fill('UI audit - attachment recovery '+Date.now());
 await page.locator('#field-attachments').setInputFiles({name:'ui-audit.txt',mimeType:'text/plain',buffer:Buffer.from('Dedicated Diwan UI test attachment')});
 await page.route('**/api/method/upload_file',route=>route.fulfill({status:500,contentType:'application/json',body:'{}'}));
 await page.locator('#submit-btn').click();
 await page.waitForFunction(()=>document.querySelector('#form-message').innerText.includes('some attachments failed'));
 assert.match(await page.locator('#attachment-list').innerText(),/ui-audit.txt/);
 assert.match(page.url(),/\/submit/);
 assert.equal(await page.locator('#submit-btn').isEnabled(),true);
 console.log('PASS: rejected upload keeps draft and pending attachment; no false submission.');
 await page.unroute('**/api/method/upload_file');
 await page.locator('#save-draft-btn').click();
 await page.waitForFunction(()=>document.querySelector('#form-message').innerText.includes('Saved as draft.'));
 assert.equal(await page.locator('#attachment-list').innerText(),'');
 await page.locator('#submit-btn').click();
 await page.waitForURL('**/diwan/requests?name=*');
 const requestUrl=page.url();
 console.log('PASS: retry uploads attachment and submits the same draft:',decodeURIComponent(requestUrl.split('name=')[1]));
 const lang=await page.locator('.diwan-navbar__lang a[lang="ar"]').getAttribute('href');
 assert.ok(lang.includes('name='));
 await page.goto(base+lang,{waitUntil:'networkidle'});
 assert.equal(await page.locator('.diwan-app').getAttribute('dir'),'rtl');
 console.log('PASS: language switch retains record and renders RTL.');
 await page.setViewportSize({width:360,height:800});
 await page.goto(base+'/diwan/submit?_lang=ar',{waitUntil:'networkidle'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('[data-diwan-hamburger]').click();
 assert.equal(await page.locator('[data-diwan-hamburger]').getAttribute('aria-expanded'),'true');
 assert.equal(await page.evaluate(()=>document.activeElement.hasAttribute('data-diwan-close')),true);
 await page.keyboard.press('Shift+Tab');
 assert.equal(await page.evaluate(()=>document.querySelector('[data-diwan-drawer]').contains(document.activeElement)),true);
 await page.screenshot({path:'/tmp/diwan-mobile-drawer-ar.png'});
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('[data-diwan-drawer]').isVisible(),false);
 assert.equal(await page.evaluate(()=>document.activeElement.hasAttribute('data-diwan-hamburger')),true);
 await page.screenshot({path:'/tmp/diwan-submit-mobile-ar.png',fullPage:true});
 console.log('PASS: 360px RTL layout, drawer focus trap, Escape, focus restoration.');
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(base+'/diwan/queue?_lang=en',{waitUntil:'networkidle'});
 await page.screenshot({path:'/tmp/diwan-queue-desktop.png'});
 const filter=page.locator('.diwan-table-tools input');
 await filter.fill('NO-MATCH-UI-AUDIT');
 assert.equal(await page.locator('.diwan-table tbody tr:visible').count(),0);
 await filter.fill('attachment recovery');
 assert.ok(await page.locator('.diwan-table tbody tr:visible').count()>0);
 console.log('PASS: queue filter and recoverable empty state.');
 assert.deepEqual(errors,[]);
 console.log('PASS: no portal JavaScript errors.');
 await page.close();
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
